name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Create nuget.config
      env:
        nuget_config: ${{ secrets.nuget_config }}
      run: echo $nuget_config > src/nuget.config
    - name: Build with dotnet
      run: dotnet build src/LobbyAPI.csproj
    - name: Run tests
      run: dotnet test tests/LobbyAPI.Tests.csproj
